/**
 * Semantic Parser
 * 
 * Parses Typst source code back into a structured SemanticDocument.
 * Uses the stable identifier comments (// id: ...) to recreate the section tree.
 */

import { SemanticDocument, SemanticSection, DocumentStructure, PageInfo, DocumentMetadata } from './types';

/**
 * Parses Typst source with ID comments into a SemanticSection tree.
 * Note: This is an optimistic parser that assumes the source follows 
 * the structure generated by our Semantic Generator.
 */
export function parseTypstSource(
    source: string,
    pageInfo: PageInfo[],
    metadata: DocumentMetadata
): SemanticSection[] {
    const sections: SemanticSection[] = [];
    const lines = source.split('\n');
    let currentSection: Partial<SemanticSection> | null = null;
    let contentAccumulator: string[] = [];
    let currentPageIndex = 0;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();

        // Detect page breaks to track current page index
        if (line === '#pagebreak()') {
            currentPageIndex++;
            continue;
        }

        // Detect stable ID comments
        const idMatch = line.match(/^\/\/\s*id:\s*([a-zA-Z0-9_-]+)/);
        if (idMatch) {
            // If we were already building a section, flush it
            if (currentSection && currentSection.id) {
                currentSection.typstContent = contentAccumulator.join('\n').trim();
                sections.push(currentSection as SemanticSection);
            }

            // Start new section
            const id = idMatch[1];
            currentSection = {
                id,
                pageIndex: currentPageIndex,
                meta: {
                    confidence: 1.0,
                    source: 'heuristic',
                    columnIndex: 0,
                    sourceRunCount: 1
                },
                styles: {} // Styles will be extracted or kept as empty if not needed
            };

            // Determine type from ID prefix
            if (id.startsWith('heading')) currentSection.type = 'heading';
            else if (id.startsWith('para')) currentSection.type = 'paragraph';
            else if (id.startsWith('list')) currentSection.type = 'list';
            else if (id.startsWith('table')) currentSection.type = 'table';
            else if (id.startsWith('image')) currentSection.type = 'image';
            else currentSection.type = 'paragraph';

            contentAccumulator = [];
            continue;
        }

        // Accumulate content if we are inside a section
        if (currentSection) {
            // Skip empty lines at the very beginning of a section
            if (contentAccumulator.length === 0 && line === '') continue;
            contentAccumulator.push(lines[i]); // Use original line (preserve indentation)
        }
    }

    // Flush last section
    if (currentSection && currentSection.id) {
        currentSection.typstContent = contentAccumulator.join('\n').trim();
        sections.push(currentSection as SemanticSection);
    }

    // Post-process sections to extract plain text content
    return sections.map(section => {
        // Extract content from typst markup
        // e.g., #text(size: 14pt, weight: "bold")[Title] -> Title
        // e.g., #emph[Text] -> Text
        let content = section.typstContent;

        // Remove basic Typst wrappers for plain text display
        content = content
            .replace(/^#text\([^)]*\)\[(.*)\]$/s, '$1')
            .replace(/^#emph\[(.*)\]$/s, '$1')
            .replace(/^#underline\[(.*)\]$/s, '$1')
            .replace(/^#align\([^)]*\)\[(.*)\]$/s, '$1');

        return {
            ...section,
            content: content.trim()
        } as SemanticSection;
    });
}
